nuplan:
  map_version: nuplan-maps-v1.0
scenario_filter:
  scenario_types:
  - stationary
  - on_intersection
  - on_pickup_dropoff
  - near_pedestrian_on_crosswalk
  - traversing_intersection
  - on_traffic_light_intersection
  - medium_magnitude_speed
  - traversing_traffic_light_intersection
  scenario_tokens: null
  log_names:
  - 2021.05.12.22.00.38_veh-35_01008_01518
  - 2021.05.12.22.28.35_veh-35_00620_01164
  - 2021.05.12.23.36.44_veh-35_00152_00504
  - 2021.05.12.23.36.44_veh-35_01133_01535
  - 2021.05.12.23.36.44_veh-35_02035_02387
  map_names:
  - us-nv-las-vegas-strip
  num_scenarios_per_type: 5
  limit_total_scenarios: 20
  timestamp_threshold_s: null
  ego_displacement_minimum_m: null
  expand_scenarios: false
  remove_invalid_goals: true
  shuffle: true
